### PR TITLE
Lint warnings, missing dependency, bug fixes

### LINKED ISSUE #77: Missing [cursor:pointer] on user-avatar in the main toolbar
**Description:**
When hovering over the user avatar in the main toolbar, the cursor does not change to a pointer. This behavior is inconsistent with the expected user experience, where the cursor should indicate that the avatar is clickable.

**Steps:**
1. Locate the main toolbar at the top of the page
2. Hover over the user avatar located in the main toolbar

**Expected:**
When hovering over the user avatar, the cursor should change to a pointer [cursor: pointer;], indicating that it is an interactive element.

**Actual:**
The cursor remains as the default arrow, not indicating that the user avatar is clickable.

**Screenshots:**
Image

### PR DESCRIPTION
**Pull request by rkusan00**
This PR adresses lint warnings, replaces deprecated ::v-deep adds missing type dependency. Fixes #77 #79

### CODE REVIEW

**Review by underscope — APPROVED** [review]

File: apps/frontend/components/common/AppBar.vue [hunk 1]
```diff
@@ -46,7 +46,7 @@
             :img-url="user.imgUrl"
             aria-label="User menu"
             class="mx-5"
-            tabindex="0"
+            tag="button"
```
Comment (underscope) [inline apps/frontend/components/common/AppBar.vue:49]: 🐐

**Review by underscope — APPROVED** [review]
💅💯
